### ISSUE TITLE
Problem running in a Virtual Environment- "No such file or directory: 'config.schema.yaml'

### ISSUE THREAD

**Issue by BusterMcGeee** [flecmart/keep2todoist#18]
First off, two things: First, THANK YOU for this script. Second, I'm technically-savvy but a beginner with python and coding in general.

My issue: In an effort to eventually run this script as a Windows Service, I'm first trying to get it to run in a Virtual Environment. I've set one up and activated it but I get this error message when I try to launch the app.py script:

(k2tl) C:\pyvirtuals\k2tl\Scripts>python c:\pyapps\k2tl\app\app.py
Traceback (most recent call last):
  File "c:\pyapps\k2tl\app\app.py", line 153, in <module>
    configManager = ConfigManager('config.schema.yaml', 'config.yaml')
  File "c:\pyapps\k2tl\app\configManager.py", line 18, in __init__
    self.schema = yamale.make_schema(path_to_schema)
  File "C:\pyvirtuals\k2tl\lib\site-packages\yamale\yamale.py", line 10, in make_schema
    raw_schemas = readers.parse_yaml(path, parser, content=content)
  File "C:\pyvirtuals\k2tl\lib\site-packages\yamale\readers\yaml_reader.py", line 34, in parse_yaml
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.schema.yaml'

This script DOES work perfectly when manually run from outside the VE, I just haven't been able to get it running as a Service. Although I've followed instructions to the letter in setting up a VE for pythons scripts, I also understand that this may have nothing to do with your code, but I wanted to mention it in case you could see anything obvious.

Thanks for your time!

**Comment by flecmart** [comment]
Hey there,

The error is, that the `config.schema.yaml` is not found in the working directory. I suspect your call to the virtual environment causes the app to use the wrong woring directory.

Instead of `python c:\pyapps\k2tl\app\app.py`

can you try

```
cd c:\pyapps\k2tl\app
python app.py
```

The easiest and most reliable way to start this as a service on any environment is using docker I think. For personal use you can install and use Docker Desktop for Windows for free and then use the command line to start the app with docker-compose (command is in the README). You don't need to understand everything about containers to be able to use this - so don't be afraid to try it :-)

**Comment by BusterMcGeee** [comment]
Thank you, that did it! I can manually start the script in a virtual environment and I've got the service running, but it's not outputting anything. I'll take your advice and try Docker. 

Thanks for your time

**Comment by flecmart** [comment]
You're welcome! What do you mean by it's not outputting anything? Nothing on the console? And the sync does not work?

**Comment by BusterMcGeee** [comment]
I mentioned it not "outputting anything" in the context of having set up output and error logs with the service which the service wasn't updating. I've realized that for some reason as a service it makes enough Google authorization requests that it exceeds my per-minute limit (or it's possible I had another instance of keep2todoist running at the time...) and I keep getting signed out of my Google accounts. For one bright shining moment the service was working as expected, though! I might try increasing the update interval and see if I can get it working.

First though, Docker- Thanks, I've been trying to make it work- I've installed it and I've successfully imported your script into a container, I'm now just sorting through a few issues with the software requirements like turning on Windows 10 virtualization. Windows does NOT like it when I turn virtualization on in my BIOS... Ahh, the joys of DIY! 

Thanks again for your time and attention.

**Comment by flecmart** [comment]
Hey again,

Being logged out of your google account indeed is a hint that the service is running parallel somewhere else or that the update interval maybe is too small. I got problems in the beginning of this development that I was logged out my Google account every other day and it was because google created a new device for every call to the keep api. I fixed those problems though by passing a fixed ID, so that google associates every call from this app with the same (virtual) device. This should not be a problem anymore.

What is your configured update interval? I suppose google has implemented some kind of rate limiting.

**Comment by flecmart** [comment]
closing this for now - don't hesitate to reopen if you continue to have problems
