### ISSUE TITLE
Suddenly, Errors!

### ISSUE THREAD

**Issue by maarxx** [flecmart/keep2todoist#25]
Suddenly, Errors!

I've been using this for a while without problems and I just noticed this morning that (A) it wasn't working (items sitting in my Keep List) and (B) i got logged out of my Google Account on all of my Android phones.

Checking the server, the application was in a tight crash loop with verbose output.

I cycled my Google App Password and my Todoist API key, but trying to start it again yielded similar looking errors, and trying again also logged out my Google Account on all my Android phones again.

I also blindly did a `git fetch && git pull` to latest `master`, I was somewhere back in September. Didn't appear to change anything.

<details>
<summary>CLICK TO EXPAND ERROR LOG</summary>

```
keep2todoist  | requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.todoist.com/rest/v1/tasks
keep2todoist exited with code 1
keep2todoist  | INFO:root:Loading configuration...
keep2todoist  | INFO:root:Start scheduler...
keep2todoist  | INFO:root:Transfering Tasks list from keep to todoist...
keep2todoist  | INFO:root:Transfering Shopping list from keep to todoist...
keep2todoist  | Traceback (most recent call last):
keep2todoist  |   File "/app/./app.py", line 63, in <module>
keep2todoist  |     schedule.run_all()
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 787, in run_all
keep2todoist  |     default_scheduler.run_all(delay_seconds=delay_seconds)
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 118, in run_all
keep2todoist  |     self._run_job(job)
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 172, in _run_job
keep2todoist  |     ret = job.run()
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 661, in run
keep2todoist  |     ret = self.job_func()
keep2todoist  |   File "/app/./app.py", line 46, in update
keep2todoist  |     transfer_list(keep_list_name, parse_key(keep_list, 'todoist_project'), parse_key(keep_list, 'due_str_en'))
keep2todoist  |   File "/app/./app.py", line 36, in transfer_list
keep2todoist  |     todoist_api.add_task(content=item.text, due_string=due, due_lang='en')
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/todoist_api_python/api.py", line 60, in add_task
keep2todoist  |     task = post(self._session, endpoint, self._token, data=data)
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/todoist_api_python/http_requests.py", line 45, in post
keep2todoist  |     response.raise_for_status()
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
keep2todoist  |     raise HTTPError(http_error_msg, response=self)
keep2todoist  | requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.todoist.com/rest/v1/tasks
keep2todoist exited with code 1
keep2todoist  | INFO:root:Loading configuration...
keep2todoist  | INFO:root:Start scheduler...
keep2todoist  | INFO:root:Transfering Tasks list from keep to todoist...
keep2todoist  | INFO:root:Transfering Shopping list from keep to todoist...
keep2todoist  | Traceback (most recent call last):
keep2todoist  |   File "/app/./app.py", line 63, in <module>
keep2todoist  |     schedule.run_all()
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 787, in run_all
keep2todoist  |     default_scheduler.run_all(delay_seconds=delay_seconds)
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 118, in run_all
keep2todoist  |     self._run_job(job)
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 172, in _run_job
keep2todoist  |     ret = job.run()
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/schedule/__init__.py", line 661, in run
keep2todoist  |     ret = self.job_func()
keep2todoist  |   File "/app/./app.py", line 46, in update
keep2todoist  |     transfer_list(keep_list_name, parse_key(keep_list, 'todoist_project'), parse_key(keep_list, 'due_str_en'))
keep2todoist  |   File "/app/./app.py", line 36, in transfer_list
keep2todoist  |     todoist_api.add_task(content=item.text, due_string=due, due_lang='en')
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/todoist_api_python/api.py", line 60, in add_task
keep2todoist  |     task = post(self._session, endpoint, self._token, data=data)
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/todoist_api_python/http_requests.py", line 45, in post
keep2todoist  |     response.raise_for_status()
keep2todoist  |   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
keep2todoist  |     raise HTTPError(http_error_msg, response=self)
keep2todoist  | requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.todoist.com/rest/v1/tasks
keep2todoist exited with code 1
```
</details>

**Comment by maarxx** [comment]
I also blindly did a `git fetch && git pull` to latest `master`, I was somewhere back in September.

Didn't appear to change anything.

**Comment by flecmart** [comment]
Hey,

Is the error you get with the newest release the same one? Because it is
todoist API V1 that is blocking here and I migrated to use V2 a while ago I
think.

Being logged out of Google accounts was a problem for me, too in the first
version. All though with the current release it should work without
problems (at least it does for me).

Can you restart the current app and paste the log here?

maarxx ***@***.***> schrieb am Fr., 14. Apr. 2023, 19:18:

**Comment by maarxx** [comment]
I once again had forgotten that I have to do `docker-compose build` in between `git fetch && git pull` <-> `docker-compose up`.

I think that fixed it, I think it's working now, thanks so much, sorry to bother.

**Comment by flecmart** [comment]
No worries. 🙂
