### ISSUE TITLE
gkeepapi error

### ISSUE THREAD

**Issue by khaberz** [flecmart/keep2todoist#56]
Hi, I had to change my Google app password (not sure when it last worked), updated my docker image and now I am seeng the below error:

`[khaberz@denode ~]$ sudo docker run -v /home/khaberz/config.yaml:/app/config.yaml --restart always ghcr.io/flecmart/keep2todoist:latest
2023-12-12 16:49:29 configManager-INFO: validating configuration with schema 'config.schema.yaml'
2023-12-12 16:49:29 configManager-INFO: schema validation passed 👍
2023-12-12 16:49:29 configManager-INFO: configuration validation passed 👍
2023-12-12 16:49:29 configManager-INFO: updated config: config.yaml
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 214, in load
    self._load(raw)
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 291, in _load
    self._title = raw['webLink']['title']
                  ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'title'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app.py", line 169, in <module>
    keep.login(configManager.config['google_username'], configManager.config['google_password'], device_id='3ee9002270d00157')
  File "/venv/lib/python3.11/site-packages/gkeepapi/__init__.py", line 699, in login
    self.load(auth, state, sync)
  File "/venv/lib/python3.11/site-packages/gkeepapi/__init__.py", line 749, in load
    self.sync(True)
  File "/venv/lib/python3.11/site-packages/gkeepapi/__init__.py", line 1024, in sync
    self._sync_notes(resync)
  File "/venv/lib/python3.11/site-packages/gkeepapi/__init__.py", line 1074, in _sync_notes
    self._parseNodes(changes["nodes"])
  File "/venv/lib/python3.11/site-packages/gkeepapi/__init__.py", line 1110, in _parseNodes
    node = _node.from_json(raw_node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 1930, in from_json
    node.load(raw)
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 214, in load
    self._load(raw)
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 1191, in _load
    super(TopLevelNode, self)._load(raw)
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 1046, in _load
    self.annotations.load(raw['annotationsGroup'])
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 214, in load
    self._load(raw)
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 524, in _load
    annotation = self.from_json(raw_annotation)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 505, in from_json
    annotation.load(raw)
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 214, in load
    self._load(raw)
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 450, in _load
    self._entries[key] = NodeAnnotations.from_json({key: entry})
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 505, in from_json
    annotation.load(raw)
  File "/venv/lib/python3.11/site-packages/gkeepapi/node.py", line 216, in load
    raise_from(exception.ParseException('Parse error in %s' % (type(self)), raw), e)
  File "/venv/lib/python3.11/site-packages/future/utils/__init__.py", line 406, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
gkeepapi.exception.ParseException: Parse error in <class 'gkeepapi.node.WebLink'>`

**Comment by flecmart** [comment]
Hey,

This happens because of migrated notes from google assistant. Check for
newly created lists in your Google keep that were created automatically and
remove them if they are duplicates to your original lists. Restart and it
should work again.

I had the same issue. It was fixed in the newest version of gkeepapi, but
at the moment I cannot upgrade because other dependencies make the
authentication to Google fail and I don't have figured out a working
combination yet.

khaberz ***@***.***> schrieb am Di., 12. Dez. 2023, 17:54:

**Comment by khaberz** [comment]
That did the job, Thank you so much!

**Comment by marothe** [comment]
@flecmart

I have the same error here, also had a random list from Google Assistant in my google keep.

But deleting that list and restarting the container did not fix this, still get the same erorr here. 

Any idea or should I just wait for a fix regarding gkeepapi?

Thank you so much advance!

**Comment by khaberz** [comment]
@marothe Delete the list from keep's trash bin and try again

**Comment by marothe** [comment]
wow, had to delete it from archive, then from bin again - what strange UX behavior tbh.

This did the trick, thank you so much!
